name: Test profile generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Run setup.sh
      run: |
        source setup.sh
    
    - name: Run webapp
      run: |
        # We background this so we can run a curl command
        python webapp.py runserver --debug &
    
    - name: Wait 2 seconds
      run: |
        sleep 2
    
    - name: curl endpoint
      run: |
        curl localhost:5000

    - name: Test a *.perf file exists
      run: |
        if compgen -G "perf_test/GET.*.prof" > /dev/null ; then
          echo 'Perf file exists! Success.'
          exit 0;
        else
          echo 'Perf file *DOES NOT* exist! Failing.'
          exit 1;
        fi
